namespace XamDataGridFilterAutogeneratedColumns
{
    public class Customer
    {
        public Customer(string firstName, string lastName, int age, string sex)
        {
            FirstName = firstName;
            LastName = lastName;
            Age = age;
            Sex = sex;
        }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
    }
}
