using System.Windows;
namespace XamDataGridFilterAutogeneratedColumns
{
    /// <summary>
    /// Interaktionslogik für MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            //note: if you want to set the viewModel before, you need to add the fieldlayoutchanged event to the behavior for the init
            DataContext = new MainWindowsViewModel();
        }
    }
}
